models/item.py
from typing import Dict
import re
import requests
import uuid
from dataclasses import dataclass, field
from bs4 import BeautifulSoup
from models.model import Model
from common.database import Database

@dataclass(eq=Fasle)
class Item(Model):
    collection = str = field(init=False, default="items")
    url: str
    tag_name: str
    query: Dict
    price: float = field(default=None)
    _id: str = field(default_factory=lambda: uuid.uuid4())

    def load_price(self) -> float:
        response = requests.get(self.url)
        content = response.content
        soup = BeautifulSoup(content, "html.parser")
        element = soup.find(self.tag_name, self.query)
        string_price = element.text.strip()

        pattern = re.compile(r"(\d+,?\d*\.\d\d)") 
        match = pattern.search(string_price)
        found_price = match.group(1)
        without_commas = found_price.replace(",", "")
        self.price = float(without_commas)
        return self.price

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "url": self.url,
            "tag_name": self.tag_name,
            "price": self.price,
            "query": self.query
        }


    def save_to_mongo(self):
        Database.insert(self.collection, self.json())

    @classmethod
    def get_by_id(cls, _id: str) -> "Item":
        item_json = Database.find_one("items", {"_id": _id})
        return cls(**item_json)

views/items.py
import json
from models.item import Item
from flask import Blueprint, render_template, request

item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/')
def index():
    items = Item.all()
    return render_template('items/index.html', items=items)

@item_blueprint.route('/new', methods=['GET', 'POST'])
def new_item():
    if request.method == 'POST':
        url = request.form['url']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Item(url, tag_name, query).save_to_mongo()

    return render_template('items/new_item.html')

templates/items/index.html
{% extends "base.html" %}

{% block content %}
<header> 
    <h1>Item</h1>
</header>
<section>
    <div class="list-group mb-3">
        {% for item in items %}
            <div class="list-group-item">
                <h4>Item</h4>
                <p>
                    <a href="{{item.url}}">{{ item.url }}</a>
                </p>
            </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="{{ url_for('items.new_item')}}">
</section>
{% endblock %}

templates/items/new_item.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Item</h1></header>
    <section class="create-item-form">
        <form method="post" action="/">
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="https://..."/>
            </div>
            <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="type" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp"/>
            <small class="form-text text-muted" id="tagNameHelp">
                What is the Html tag of the item that contains the item price?
            </small>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" placeholder='{"id": "..."}' aria-describedby="queryHelp"/>
                <small class="form-text text-muted">
                    What JSON query would we have to do to find the specific tag with the price?
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
            </form>







        </form>
    </section>
{% endblock %}